// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearRecentDirectories() {
  return window['go']['main']['App']['ClearRecentDirectories']();
}

export function GetFilterConfig() {
  return window['go']['main']['App']['GetFilterConfig']();
}

export function GetRecentDirectories() {
  return window['go']['main']['App']['GetRecentDirectories']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ResetFilterConfig() {
  return window['go']['main']['App']['ResetFilterConfig']();
}

export function RevealInFileManager(arg1) {
  return window['go']['main']['App']['RevealInFileManager'](arg1);
}

export function SaveFilterConfig(arg1) {
  return window['go']['main']['App']['SaveFilterConfig'](arg1);
}

export function SaveXMLFile(arg1, arg2) {
  return window['go']['main']['App']['SaveXMLFile'](arg1, arg2);
}

export function ScanLocalDirectory(arg1) {
  return window['go']['main']['App']['ScanLocalDirectory'](arg1);
}

export function ScanLocalDirectoryByPath(arg1) {
  return window['go']['main']['App']['ScanLocalDirectoryByPath'](arg1);
}

export function SelectAndScanLocalDirectory() {
  return window['go']['main']['App']['SelectAndScanLocalDirectory']();
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}
