// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SaveXMLFile(arg1, arg2) {
  return window['go']['main']['App']['SaveXMLFile'](arg1, arg2);
}

export function ScanLocalDirectory(arg1) {
  return window['go']['main']['App']['ScanLocalDirectory'](arg1);
}

export function SelectAndScanLocalDirectory() {
  return window['go']['main']['App']['SelectAndScanLocalDirectory']();
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}
