// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function Greet(arg1:string):Promise<string>;

export function ScanLocalDirectory(arg1:string):Promise<model.GingestResponse>;

export function SelectAndScanLocalDirectory():Promise<model.GingestResponse>;

export function SelectDirectory():Promise<string>;
